### ISSUE TITLE
Increase height of stand-offs inside bottom case by 1 mm to prevent BOOTSEL from accidentially being pressed

### ISSUE THREAD

**Issue by aentinger** [generationmake/OpenCyphalPicoBase#10]
Adjust the rest of the design accordingly!

![picocase](https://github.com/generationmake/OpenCyphalPicoBase/assets/3931733/a6dfa37c-58b8-49b0-a54b-b0c675fc0a23)

**Comment by generationmake** [comment]
different approach: reduce thickness of the bottom plate in the area of the button by 1mm.

**Comment by aentinger** [comment]
But make the area spacey enough, as any negative space always gets smaller during actual printing.

**Comment by aentinger** [comment]
On further consideration: just increase the diameter of the already existing hole .
