### ISSUE TITLE
add protection to CAN

### ISSUE THREAD

**Issue by generationmake** [generationmake/OpenCyphalPicoBase#7]
Add some ESD protection to CAN bus.
For example with PESD2CAN on data lines.
https://assets.nexperia.com/documents/data-sheet/PESD2CAN.pdf
and TVS diode on bus voltage.

**Comment by aentinger** [comment]
Let's discuss that. At one of my previous employers PESD2CAM added an unacceptable capacitance on the bus. Ultimately we got rid of them.
